# This file contains possible settings you can use to configure Phantom-in-a-box 

[global]
log_path = piab.log
# Sets the log_path for the logging file

log_level = INFO
# Sets the log level for the logging
# Possible values: INFO, ERROR

[range_settings]
key_name = phantom-in-a-box
# Specify the name of the EC2 key pair name
# This is only needed for modes: terraform and packer

ip_whitelist = 0.0.0.0/0
# Specify the IP whitelist for the aws instances
# This is only needed for modes: terraform and packer

#private_key_path = ~/.ssh/id_rsa
private_key_path = ~/.ssh/phantom-in-a-box
# Specify the path to your private SSH key
# This is only needed for modes: terraform and packer

region = eu-west-1
# Specify the aws region in which you want to build the phantom-server in
# please ensure that aws_cli has the same region specified
# This is only needed for modes: terraform and packer


[phantom_settings]
phantom_community_username = <yourname>@splunk.com 
# Specify the username needed to login to my.phantom.us to download Phantom
# This must be changed to a real username
# You can register under my.phantom.us

phantom_community_password = <yourpassword> 
# Specify the password used to login to my.phantom.us to download Phantom
# This must be changed to a real password
# You can register under my.phantom.us

phantom_admin_password = Phantom-!n-a-b0x!
# Specify the password that will be used to login to the new Phantom instance as admin
# It is recommended that you change this value

#pov_repo = https://git.splunk.com/deking/phantom_pov/raw/master/
#pov_repo = https://git.splunk.com/users/deking/repos/phantom_pov/raw/
pov_repo = https://github.com/networkslayer/phantom_pov/raw/master/
# Specify where the Initial POV configuration should be installed from


phantom_app_repo = http://repo.phantom.us/phantom/4.10/apps/x86_64/
# Specify where the phantom apps to install are 

#phantom_version = 4.9.35731-1
phantom_version = 4.10.1.45070-1
# Specific version of Phantom to install

[environment]
# specify your environment by enabling (1) or disabling (0) machines

phantom_server = 1
# enable a phantom server
# possible values: 1, 0

[phantom_server]
# customize the phantom server

phantom_server_private_ip = 10.0.1.13
# specify the phantom server's private ip
# for mode terraform should be in subnet: 10.0.1.0/24

[customer_environment]
company_name = MyPrincipalCompany 
# Specify the company name 

customer_internal_domain = acme.local
# This is used for the Phantom Base URL

phantom_timezone = UTC
# Specify the timezone the system belongs to

customer_system_administrator = abraham.lincoln@acme.local
# Specify the system admin or distribution list receiving system-level alerts

