Vagrant.configure("2") do |config| 
 
config.vm.define "piab-phantom-server" do |config|
  VM_NAME_P= "piab-phantom-server"
  config.vm.box = "centos/7"
  config.vm.hostname = "#{VM_NAME_P}"
  config.vm.boot_timeout = 600
  config.vm.network "forwarded_port", guest: 443, host: 8443, protocol: "tcp"
  config.vm.network :private_network, ip: "10.0.1.13"

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbooks/phantom_server.yml"
      ansible.config_file = "../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
      ansible.extra_vars = {
        phantom_admin_password: 'Phantom-!n-a-b0x!',
        phantom_community_username: 'deking@splunk.com',
        phantom_community_password: 'T0sser123',
        phantom_server_private_ip: '10.0.1.13'
      }
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{VM_NAME_P}"
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--cpus", 4]
  end
end


end