

- name: Download Playbook POV_Excessive_Failed_Logons
  get_url:
    url: "{{pov_repo}}playbooks/POV_Excessive_Failed_Logons.tgz"
    dest: /tmp
      
- name: Read Playbook POV_Excessive_Failed_Logons
  slurp:
    src:  /tmp/POV_Excessive_Failed_Logons.tgz
  register: file

- name: Installing POV_Excessive_Failed_Logons playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Accept_Event Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Accept_Event.tgz"
    dest: /tmp

- name: Read Playbook POV_Accept_Event
  slurp:
    src:  /tmp/POV_Accept_Event.tgz
  register: file

- name: Installing POV_Accept_Event playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Network_Indicator_Enrichment Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Network_Indicator_Enrichment.tgz"
    dest: /tmp

- name: Read Playbook PPOV_Network_Indicator_Enrichment
  slurp:
    src:  /tmp/POV_Network_Indicator_Enrichment.tgz
  register: file

- name: Installing POV_Network_Indicator_Enrichment playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Rare_Process_Case_-_Containment Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Rare_Process_Case_-_Containment.tgz"
    dest: /tmp

- name: Read Playbook POV_Rare_Process_Case_-_Containment
  slurp:
    src:  /tmp/POV_Rare_Process_Case_-_Containment.tgz
  register: file

- name: Installing POV_Rare_Process_Case_-_Containment playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Rare_Process_Case_-_Preparation Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Rare_Process_Case_-_Preparation.tgz"
    dest: /tmp

- name: Read Playbook POV_Rare_Process_Case_-_Preparation
  slurp:
    src:  /tmp/POV_Rare_Process_Case_-_Preparation.tgz
  register: file

- name: Installing POV_Rare_Process_Case_-_Preparation playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Rare_Process_Case__-_Identification Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Rare_Process_Case__-_Identification.tgz"
    dest: /tmp

- name: Read Playbook POV_Rare_Process_Case__-_Identification
  slurp:
    src:  /tmp/POV_Rare_Process_Case__-_Identification.tgz
  register: file

- name: Installing POV_Rare_Process_Case__-_Identification playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Review_Indicators Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Review_Indicators.tgz"
    dest: /tmp

- name: Read Playbook POV_Review_Indicators
  slurp:
    src:  /tmp/POV_Review_Indicators.tgz
  register: file

- name: Installing POV_Review_Indicators playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Sinkhole_or_Block_External_Indicators Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Sinkhole_or_Block_External_Indicators.tgz"
    dest: /tmp

- name: Read Playbook POV_Sinkhole_or_Block_External_Indicators
  slurp:
    src:  /tmp/POV_Sinkhole_or_Block_External_Indicators.tgz
  register: file

- name: Installing POV_Sinkhole_or_Block_External_Indicators playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Ticketing Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Ticketing.tgz"
    dest: /tmp

- name: Read Playbook POV_Ticketing
  slurp:
    src:  /tmp/POV_Ticketing.tgz
  register: file

- name: Installing POV_Ticketing playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_EC2_Instance_Investigation Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_EC2_Instance_Investigation.tgz"
    dest: /tmp

- name: Read Playbook POV_EC2_Instance_Investigation
  slurp:
    src:  /tmp/POV_EC2_Instance_Investigation.tgz
  register: file

- name: Installing POV_EC2_Instance_Investigation.tgz playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Hunt_Email_Indicators Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Hunt_Email_Indicators.tgz"
    dest: /tmp

- name: Read Playbook POV_Hunt_Email_Indicators
  slurp:
    src:  /tmp/POV_Hunt_Email_Indicators.tgz
  register: file

- name: Installing POV_Hunt_Email_Indicators playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json



- name: Download POV_EC2_AWS_Context Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_EC2_AWS_Context.tgz"
    dest: /tmp

- name: Read Playbook POV_EC2_AWS_Context
  slurp:
    src:  /tmp/POV_EC2_AWS_Context.tgz
  register: file

- name: Installing POV_EC2_AWS_Context playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_malicious_insider_containment Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_malicious_insider_containment.tgz"
    dest: /tmp

- name: Read Playbook POV_malicious_insider_containment
  slurp:
    src:  /tmp/POV_malicious_insider_containment.tgz
  register: file

- name: Installing POV_malicious_insider_containment playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Network_URL_Enrichment Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Network_URL_Enrichment.tgz"
    dest: /tmp

- name: Read Playbook POV_Network_URL_Enrichment
  slurp:
    src:  /tmp/POV_Network_URL_Enrichment.tgz
  register: file

- name: Installing POV_Network_URL_Enrichment playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_EC2_Remote_Probe_Context Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_EC2_Remote_Probe_Context.tgz"
    dest: /tmp

- name: Read Playbook POV_EC2_Remote_Probe_Context
  slurp:
    src:  /tmp/POV_EC2_Remote_Probe_Context.tgz
  register: file

- name: Installing POV_EC2_Remote_Probe_Context playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Phishing_Preflight Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Phishing_Preflight.tgz"
    dest: /tmp

- name: Read Playbook POV_Phishing_Preflight
  slurp:
    src:  /tmp/POV_Phishing_Preflight.tgz
  register: file

- name: Installing POV_Phishing_Preflight playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_AddContext_LDAP Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_AddContext_LDAP.tgz"
    dest: /tmp

- name: Read Playbook POV_AddContext_LDAP
  slurp:
    src:  /tmp/POV_AddContext_LDAP.tgz
  register: file

- name: Installing POV_AddContext_LDAP playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Network_IP_Enrichment Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Network_IP_Enrichment.tgz"
    dest: /tmp

- name: Read Playbook POV_Network_IP_Enrichment
  slurp:
    src:  /tmp/POV_Network_IP_Enrichment.tgz
  register: file

- name: Installing POV_Network_IP_Enrichment playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Close_Splunk_ES_Notable Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Close_Splunk_ES_Notable.tgz"
    dest: /tmp

- name: Read Playbook POV_Close_Splunk_ES_Notable
  slurp:
    src:  /tmp/POV_Close_Splunk_ES_Notable.tgz
  register: file

- name: Installing POV_Close_Splunk_ES_Notable playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json


- name: Download POV_Network_Domain_Enrichment Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Network_Domain_Enrichment.tgz"
    dest: /tmp

- name: Read Playbook POV_Network_Domain_Enrichment
  slurp:
    src:  /tmp/POV_Network_Domain_Enrichment.tgz
  register: file

- name: Installing POV_Network_Domain_Enrichment playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Phishing_Network_Indicator_Enrichment Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Phishing_Network_Indicator_Enrichment.tgz"
    dest: /tmp

- name: Read Playbook POV_Phishing_Network_Indicator_Enrichment
  slurp:
    src:  /tmp/POV_Phishing_Network_Indicator_Enrichment.tgz
  register: file

- name: Installing POV_Phishing_Network_Indicator_Enrichment playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Close_Event Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Close_Event.tgz"
    dest: /tmp

- name: Read Playbook POV_Close_Event
  slurp:
    src:  /tmp/POV_Close_Event.tgz
  register: file

- name: Installing POV_Close_Event playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_WinRM_Get_File Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_WinRM_Get_File.tgz"
    dest: /tmp

- name: Read Playbook POV_WinRM_Get_File
  slurp:
    src:  /tmp/POV_WinRM_Get_File.tgz
  register: file

- name: Installing POV_WinRM_Get_File playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_File_Reputation Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_File_Reputation.tgz"
    dest: /tmp

- name: Read Playbook POV_File_Reputation
  slurp:
    src:  /tmp/POV_File_Reputation.tgz
  register: file

- name: Installing POV_File_Reputation playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Detonate_Executable_File Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Detonate_Executable_File.tgz"
    dest: /tmp

- name: Read Playbook POV_Detonate_Executable_File
  slurp:
    src:  /tmp/POV_Detonate_Executable_File.tgz
  register: file

- name: Installing POV_Detonate_Executable_File playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Get_Sys_Info_LDAP Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Get_Sys_Info_LDAP.tgz"
    dest: /tmp

- name: Read Playbook POV_Get_Sys_Info_LDAP
  slurp:
    src:  /tmp/POV_Get_Sys_Info_LDAP.tgz
  register: file

- name: Installing POV_Get_Sys_Info_LDAP playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_SIEM_Context_Authentication_By_Host Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_SIEM_Context_Authentication_By_Host.tgz"
    dest: /tmp

- name: Read Playbook POV_SIEM_Context_Authentication_By_Host
  slurp:
    src:  /tmp/POV_SIEM_Context_Authentication_By_Host.tgz
  register: file

- name: Installing POV_SIEM_Context_Authentication_By_Host playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_SIEM_Context Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_SIEM_Context.tgz"
    dest: /tmp

- name: Read Playbook POV_SIEM_Context
  slurp:
    src:  /tmp/POV_SIEM_Context.tgz
  register: file

- name: Installing POV_SIEM_Context playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_SIEM_Context_Process_Execution_By_Host Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_SIEM_Context_Process_Execution_By_Host.tgz"
    dest: /tmp

- name: Read Playbook POV_SIEM_Context_Process_Execution_By_Host
  slurp:
    src:  /tmp/POV_SIEM_Context_Process_Execution_By_Host.tgz
  register: file

- name: Installing POV_SIEM_Context_Process_Execution_By_Host playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_SIEM_Context_Web_By_UserName Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_SIEM_Context_Web_By_UserName.tgz"
    dest: /tmp

- name: Read Playbook POV_SIEM_Context_Web_By_UserName
  slurp:
    src:  /tmp/POV_SIEM_Context_Web_By_UserName.tgz
  register: file

- name: Installing POV_SIEM_Context_Web_By_UserName playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json

- name: Download POV_Auto_Add_Workbook Playbook 
  get_url:
    url: "{{pov_repo}}playbooks/POV_Auto_Add_Workbook.tgz"
    dest: /tmp

- name: Read Playbook POV_Auto_Add_Workbook
  slurp:
    src:  /tmp/POV_Auto_Add_Workbook.tgz
  register: file

- name: Installing POV_Auto_Add_Workbook playbook
  uri:
    user: admin
    url: https://127.0.0.1/rest/import_playbook
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"playbook":"{{ file['content'] }}","scm":"local"}
    body_format: json



























































