---
# Configure phantom with credentials, apps, assets, and so on...

- name: change phantom admin password
  uri:
    url: https://127.0.0.1/rest/user_settings
    method: POST
    user: admin
    password: password
    body: {"old_password":"password","password":"{{phantom_admin_password}}"}
    body_format: json
    force_basic_auth: yes
    validate_certs: no

- name: fetch phantom api token
  uri:
    url: https://127.0.0.1/rest/ph_user/2/token
    method: GET
    user: admin
    password: "{{phantom_admin_password}}"
    force_basic_auth: yes
    validate_certs: no
  register: api_token

- name: display phantom api token
  debug:
    msg: "phantom api token is {{api_token.json.key}}"

- name: open up api allowed ip list
  uri:
    url: https://127.0.0.1/rest/ph_user/2
    method: POST
    body: '{"allowed_ips":["any"]}'
    user: admin
    password: "{{phantom_admin_password}}"
    force_basic_auth: yes
    validate_certs: no

- name: test api token
  uri:
    url: https://127.0.0.1/rest/container
    method: GET
    return_content: yes
    headers:
      ph-auth-token: "{{api_token.json.key}}"
    validate_certs: no


- name: Configuring ROI Settings
  uri:
    user: admin
    url: https://127.0.0.1/rest/system_settings/roi
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"roi_fte_gained":"on", "roi_money_saved":"on", "roi_time_saved":"on"}
    body_format: json

- name: Installing Company Name
  uri:
    user: admin
    url: https://127.0.0.1/rest/system_settings/info
    password: "{{phantom_admin_password}}"
    validate_certs: no
    force_basic_auth: yes
    method: POST
    body: {"company_name":"{{company_name}}", "fqdn":"https://phantom.{{customer_internal_domain}}"}
    body_format: json


